version: '3'

services:
  web:
    build: .
    container_name: productfeeder_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      MYSQL_HOST: db
      MYSQL_DATABASE: productfeeder
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: productfeeder_db
    environment:
      MYSQL_DATABASE: productfeeder
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - "./migrations/init.sql:/docker-entrypoint-initdb.d/1.sql"
      - productfeeder_db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: productfeeder_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  productfeeder_db_data: